% src/Adjust_Linear.m

% adjust the envelope by linear piecewise function
function result = Adjust_Linear(t)
    t_begin = t(1);
    t_len = t(end) - t(1);
    result = ...
        (t_begin <= t & t < t_begin + t_len / 6) .* (6 / t_len * (t - t_begin)) + ...
        (t_begin + t_len / 6 <= t & t < t_begin + t_len / 3) .* (1 - 1.2 / t_len * (t - t_begin - t_len / 6)) + ...
        (t_begin + t_len / 3 <= t & t < t_begin + t_len * 2/3) .* 0.8 + ...
        (t_begin + t_len * 2/3 <= t & t <= t_begin + t_len) .* (-2.4 / t_len * (t - t_begin - t_len));
end
